import type { Metadata } from "next";
import "./globals.css";
import RootProvider from "@/provider";
import { Navbar } from "@/components/core/navbar";
import { Toaster } from "@/components/ui/toaster"
import { Noto_Sans } from 'next/font/google'
import Footer from "@/components/core/footer";

const pacifico = Noto_Sans({
  weight: '400', 
  subsets: ['latin'],
  variable: '--font-pacifico'
})

export const metadata: Metadata = {
  title: "Gancy Motor Parts",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pacifico.className} antialiased`}>
        <RootProvider>
          <Navbar />
          {children}
          <Toaster />
          <Footer />
        </RootProvider>
      </body>
    </html>
  );
}
